### ISSUE TITLE
中文版ROM乱码

### ISSUE THREAD

**Issue by Macrored** [FEBuilderGBA/FEBuilderGBA#13]
为什么我打开的烈火之剑中文版.gba文件，但是是乱码的呢？我的系统是windows10 家庭版，难道需要安装特定的字体吗？
![image](https://user-images.githubusercontent.com/52482853/82733567-36738280-9d47-11ea-9367-3aa2d111da7c.png)

**Comment by FEBuilderGBA** [comment]
I have been late to contact.
I'm not sure what the your question means.

Is it a font issue in Windows 10 OS?
I can't fix an issue that only reproduces in a particular environment.
