### ISSUE TITLE
[Feature Request] Import/Export stats to plaintext or CSV

### ISSUE THREAD

**Issue by TheGameMecha** [FEBuilderGBA/FEBuilderGBA#14]
Some modders may find it useful to be able to export character/class stats and analyze them in Excel to balance and compare them and then import once finalized. As it is now, modders would need to manually type out the numbers and input them.

**Comment by FEBuilderGBA** [comment]
That feature already exists.
On each screen, double-click on the part labeled Address.
You can go to the Import/Export screen.

**Comment by TheGameMecha** [comment]
![image](https://github.com/FEBuilderGBA/FEBuilderGBA/assets/40323442/ebd2ce2e-8ce8-4edb-8e60-09b1e3dd17bb)
Double clicking on any of these 3 sections does nothing.
