### ISSUE TITLE
''Expand List'' button missing on ''Item Icon'' list

### ISSUE THREAD

**Issue by reik019** [FEBuilderGBA/FEBuilderGBA#16]
Some releases before, (Starting the 2020 branch I think) I noticed you removed the button to extend the weapon/item icons, I don't know if it is a bug, because I tested with all three ROMs I had in hand (FE6, FE7u & FE8u), and the item icon extension patch doesnt work (tested only on FE7u, as it is the version I work in), even tried to do the changes via the built-in Hex editor and nothing changes at all.

If it was removed intentionally, there is an alternative available besides the extension patch? (Yes, I'm aware that it had some bugs, like garbled icon when checking unit's inventory, but when attacking/battle anim worked fine)

**Comment by FEBuilderGBA** [comment]
To extend the item icon, ASM must be modified to reference the added icon area.
However, this patch does not exist in FE7.
Therefore, the icon cannot be expanded.
