### ISSUE TITLE
[ Not an issue just a question ] Does FEBuilder allows inserting new chapters/characters?

### ISSUE THREAD

**Issue by Kapizor** [FEBuilderGBA/FEBuilderGBA#20]
I fiddled and tinkered a little with the builder but could not find any way to insert a new character/chapter. The game's designed we can only work with whatever chapters there are or use the ones that are used for cutscenes? All is hardcoded into existing "slots"?

**Comment by FEBuilderGBA** [comment]
Except for the questions of FEBuilderGBA itself, please ask on FE Universe or discord.
