### ISSUE TITLE
When hacking FE6, game crashes when a modified conversation comes up

### ISSUE THREAD

**Issue by Unity123** [FEBuilderGBA/FEBuilderGBA#21]
See title.
Whenever I modify a conversation in FE6, it crashes the game. Nobody on the FEU discord could solve it, so I think it may be an editor bug.
[SecondAttemptAtAWorkingRom.REPORT.20210108140538.report.7z.zip](https://github.com/FEBuilderGBA/FEBuilderGBA/files/5789975/SecondAttemptAtAWorkingRom.REPORT.20210108140538.report.7z.zip)

**Comment by FEBuilderGBA** [comment]
Ask this kind of question on FEU or discord.
