### ISSUE TITLE
Predefined palette for BAD status looks wrong

### ISSUE THREAD

**Issue by delvier** [FEBuilderGBA/FEBuilderGBA#28]
I think this problem happens in FE6 and FE7J/U.
![System Icon FE7J_0841BE00](https://user-images.githubusercontent.com/70463874/115486777-4ca8fc00-a292-11eb-8888-0c85d6ab2795.png)
![Graphics Editor FE7J_0841BE00](https://user-images.githubusercontent.com/70463874/115486966-ae696600-a292-11eb-8094-9a3666f24635.png)
The first image is extracted via FEBuilderGBA with palette preset, and the second is with no palette (i.e. the address for palette being 0x0).
On the right of HP, there are DEF and AVO system icons for terrains, but this is mostly removed when the image is extracted from FEBuilder. The second set of digits are also seems wrong.

**Comment by delvier** [comment]
![Graphics Editor FE7J_41BE00](https://user-images.githubusercontent.com/70463874/115488780-0a81b980-a296-11eb-9a46-367415e90cfe.png)
For FE7J, 0x190268 (offset from the current palette: +0x60) seems to match to the actual game screen, but I might be wrong.

**Comment by FEBuilderGBA** [comment]
I fiexed FE7J/FE7U.
but,FE6 does not know the address of the palette.

**Comment by delvier** [comment]
For FE6, the image with the palette address 0x100A08 (Δ = -0x40) looks similar to the ones of FE7.

**Comment by delvier** [comment]
![190208](https://user-images.githubusercontent.com/70463874/117565387-e1618580-b0eb-11eb-9c73-80208e53aa34.png) ![190268](https://user-images.githubusercontent.com/70463874/117565388-e1fa1c00-b0eb-11eb-9e1c-4133bafae054.png)
In my opinion, the uncompressed image also seems more easy to be edited when the new palette value is used.

**Comment by FEBuilderGBA** [comment]
Thank you very much.
It wasn't in time for today's update, so I'll fix it in the next update.
