### ISSUE TITLE
Select from affinity list doesn't work as expected

### ISSUE THREAD

**Issue by laqieer** [FEBuilderGBA/FEBuilderGBA#30]
# Operation
Click an affinity in the list: `05 - Dark`
![image](https://user-images.githubusercontent.com/8841957/161395645-1c9c6e20-e807-4dd7-91a6-99585f3d2e18.png)
# Result
The affinity above is selected: `04 - Ice`
![image](https://user-images.githubusercontent.com/8841957/161395725-77c795e1-06d1-4ee8-b92e-a00ca173902c.png)
# Expected
The affinity clicked is selected: `05 - Dark`

**Comment by FEBuilderGBA** [comment]
This has already been fixed.
