### ISSUE TITLE
章タイトル名前リスト

### ISSUE THREAD

**Issue by laqieer** [FEBuilderGBA/FEBuilderGBA#7]
![image](https://user-images.githubusercontent.com/8841957/53007549-6eb85100-3472-11e9-8ccf-87084ca76333.png)
２９からはヘクトル編の章タイトルです

**Comment by FEBuilderGBA** [comment]
Fix Chapter Setting.
I think I can not display the name because there is a duplicate ID.

Because I made it possible to jump from Chapter Setting, I think that there is no problem even if the name is not displayed.
