### ISSUE TITLE
聖魔の85コマンド解析

### ISSUE THREAD

**Issue by laqieer** [FEBuilderGBA/FEBuilderGBA#8]
0x53 through 0xFF - Unused in **FE7**
They are used in **FE8**. 
[聖魔の場合は以降魔物の効果音とか](https://www58.atwiki.jp/fekai2/pages/26.html).
However, they are not parsed correctly.
![image](https://user-images.githubusercontent.com/8841957/56851098-d9d44700-693d-11e9-97cb-a220fce4630f.png)

**Comment by FEBuilderGBA** [comment]
Fixed.
